export const categoryData = [
  {
    categoryId: 1,
    categoryName: "bé an toàn",
    categoryImage: "a",
    categoryStatus: true,
    subCategoryVMs: [
      {
        subCategoryId: 2,
        categoryId: 1,
        subCategoryName: "chặn cầu thang - chặn cửa",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 3,
        categoryId: 1,
        subCategoryName: "chặn giường - thanh chắn giường",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 4,
        categoryId: 1,
        subCategoryName: "bịt ổ điện, bịt góc bàn",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 5,
        categoryId: 1,
        subCategoryName: "nhiệt kế hồng ngoại",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 6,
        categoryId: 1,
        subCategoryName: "bàn học thông minh chống gù",
        subCategoryStatus: true,
      },
    ],
  },
  {
    categoryId: 2,
    categoryName: "abc",
    categoryImage: "a",
    categoryStatus: true,
    subCategoryVMs: [
      {
        subCategoryId: 1,
        categoryId: 2,
        subCategoryName: "gối chống trào ngược cho bé sơ sinh",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 7,
        categoryId: 2,
        subCategoryName: "giường cũi cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 8,
        categoryId: 2,
        subCategoryName: "nôi điện tự động",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 9,
        categoryId: 2,
        subCategoryName: "ghế rung - nôi rung cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 10,
        categoryId: 2,
        subCategoryName: "phụ kiện cho bé ngủ",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 11,
        categoryId: 2,
        subCategoryName: "giường tầng cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 12,
        categoryId: 2,
        subCategoryName: "tủ nhựa cho bé",
        subCategoryStatus: true,
      },
    ],
  },
  {
    categoryId: 3,
    categoryName: "bé ra ngoài",
    categoryImage: "a",
    categoryStatus: true,
    subCategoryVMs: [
      {
        subCategoryId: 13,
        categoryId: 3,
        subCategoryName: "xe đẩy cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 14,
        categoryId: 3,
        subCategoryName: "xe đạp trẻ em",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 15,
        categoryId: 3,
        subCategoryName: "địu em bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 16,
        categoryId: 3,
        subCategoryName: "xe tập đi cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 17,
        categoryId: 3,
        subCategoryName: "xe đẩy ba bánh",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 18,
        categoryId: 3,
        subCategoryName: "xe đẩy đôi",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 19,
        categoryId: 3,
        subCategoryName: "ghế ngồi ô tô cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 20,
        categoryId: 3,
        subCategoryName: "nôi xách tay em bé",
        subCategoryStatus: true,
      },
    ],
  },
  {
    categoryId: 4,
    categoryName: "đồ bé chơi",
    categoryImage: "a",
    categoryStatus: true,
    subCategoryVMs: [
      {
        subCategoryId: 21,
        categoryId: 4,
        subCategoryName: "xe ô tô điện, xe hơi điện trẻ em",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 22,
        categoryId: 4,
        subCategoryName: "xe lắc cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 23,
        categoryId: 4,
        subCategoryName: "kệ để đồ chơi",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 24,
        categoryId: 4,
        subCategoryName: "bể bơi, phao bơi",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 25,
        categoryId: 4,
        subCategoryName: "thảm chơi trẻ em",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 26,
        categoryId: 4,
        subCategoryName: "cầu trượt xích đu",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 27,
        categoryId: 4,
        subCategoryName: "xe trượt scooter and ride",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 28,
        categoryId: 4,
        subCategoryName: "quây cũi nhựa",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 29,
        categoryId: 4,
        subCategoryName: "đồ chơi giáo dục",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 30,
        categoryId: 4,
        subCategoryName: "đồ chơi cho trẻ sơ sinh",
        subCategoryStatus: true,
      },
    ],
  },
  {
    categoryId: 5,
    categoryName: "đồ bé tắm",
    categoryImage: "a",
    categoryStatus: true,
    subCategoryVMs: [
      {
        subCategoryId: 31,
        categoryId: 5,
        subCategoryName: "kệ tắm em bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 32,
        categoryId: 5,
        subCategoryName: "sữa tắm, dầu gội",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 33,
        categoryId: 5,
        subCategoryName: "đo nhiệt độ tắm cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 34,
        categoryId: 5,
        subCategoryName: "chậu tắm cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 35,
        categoryId: 5,
        subCategoryName: "dụng cụ hút mũi",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 36,
        categoryId: 5,
        subCategoryName: "bàn thay tã - kệ thay tã cho bé",
        subCategoryStatus: true,
      },
    ],
  },
  {
    categoryId: 6,
    categoryName: "đồ cho mẹ",
    categoryImage: "a",
    categoryStatus: true,
    subCategoryVMs: [
      {
        subCategoryId: 37,
        categoryId: 6,
        subCategoryName: "máy hút sữa",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 38,
        categoryId: 6,
        subCategoryName: "thấm sữa, hứng sữa",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 39,
        categoryId: 6,
        subCategoryName: "đầm bầu, váy bầu",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 40,
        categoryId: 6,
        subCategoryName: "gối cho bà bầu",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 41,
        categoryId: 6,
        subCategoryName: "chắm sóc răng miệng",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 42,
        categoryId: 6,
        subCategoryName: "dụng cụ trang điểm",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 43,
        categoryId: 6,
        subCategoryName: "bồn tắm gấp gọn",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 44,
        categoryId: 6,
        subCategoryName: "ghế thư giãn",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 45,
        categoryId: 6,
        subCategoryName: "đai nịt bụng",
        subCategoryStatus: true,
      },
    ],
  },
  {
    categoryId: 7,
    categoryName: "đồ bé ăn",
    categoryImage: "a",
    categoryStatus: true,
    subCategoryVMs: [
      {
        subCategoryId: 46,
        categoryId: 7,
        subCategoryName: "bình sữa và phụ kiện ",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 47,
        categoryId: 7,
        subCategoryName: "bột ăn dặm ",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 48,
        categoryId: 7,
        subCategoryName: "sữa cho trẻ em",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 49,
        categoryId: 7,
        subCategoryName: "máy hâm sữa và thức ăn",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 50,
        categoryId: 7,
        subCategoryName: "ghế ăn dặm cho bé",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 51,
        categoryId: 7,
        subCategoryName: "máy tiệt trùng bình sữa",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 52,
        categoryId: 7,
        subCategoryName: "máy pha sữa bột",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 53,
        categoryId: 7,
        subCategoryName: "thực phẩm bổ sung vitamin",
        subCategoryStatus: true,
      },
      {
        subCategoryId: 54,
        categoryId: 7,
        subCategoryName: "nồi nấu chậm",
        subCategoryStatus: true,
      },
    ],
  },
];
